part of 'app_navigator.dart';

enum Routes {
  splash('/splash'),
  tutorial('/tutorial'),
  login('/login'),
  register('/register'),
  home('/home'),
  setting('/setting'),
  vehicleList('/vehicle_list'),
  profile('/profile'),
  profileEdit('/profileEdit'),
  chat('/chat'),
  selfIdCreaterOption('/SelfIdCreaterOption'),
  selfIdOcrOption('/SelfIdOcrOptionPage'),
  selfIdCreater('/SelfIdCreater'),
  selfIdCreaterSuccess('/SelfIdCreaterSuccess'),
  selfIdList('/SelfIdList'),
  selfIdListChoose('/SelfIdListChoose'),
  requestVerification('/RequestVerification'),
  verificationCross('/VerificationCross'),
  verificationFinish('/verificationFinish'),
  familyList('/familyList'),
  familyTree('/familyTree'),
  qrScan('/qrScan'),
  qrScanSuccess('/qrScanSuccess'),
  checkInOut('/checkInOut'),
  bankList('/bankList'),
  bankCreate('/bankCreate'),
  bankCreateSuccess('/bankCreateSuccess'),
  terms('/terms'),
  ocrId('/ocrId'),
  imageView('/imageView'),
  biography('/biography'),
  confirmRelationship('/confirmRelationship'),
  contactPicker('/contactPicker'),
  reportPage('/reportPage'),
  detailReportPage('/detailReportPage'),
  termService('/termSerVice'),
  privacyPolicy('/privacyPolicy'),
  guardPage('/guardPage'),
  requesterListPage('/requesterListPage'),
  mutualAuthRequest('/v2/mutualAuthRequest'),
  mutualAuthReceive('/v2/mutualAuthReceive'),
  mutualAuthOffline('/v2/mutualAuthOffline'),
  mutualAuthOfflineDisplay('/v2/mutualAuthOffline/display'),
  mutualAuthOfflineScan('/v2/mutualAuthOffline/scan'),
  inProcContact('/v2/inProcContact'),
  profileEditV2('/v2/profileEdit'),
  reportV2('/v2/report'),
  aiChatV2('/v2/aiChat'),
  idGenerationV2('/v2/idGeneration'),
  ;

  final String path;
  const Routes(this.path);
}
